---
title: "STA 492 2.0/ ASP 460 2.0 Data Visualisation"
editor: source
---

## Lecturer-in-charge:

Dr Thiyanga S. Talagala

## Email:

ttatalagala\@sjp.ac.lk

## Course outline:

Available on Google Classroom

## Policies and regulations:

To access important information regarding the unit, please go to the Google Classroom.

## Weekly Schedule:

## Week 1: April 22, 2026

Introduction to grammar of graphics

[The Grammar of Graphics](./week2/index.html)

## Week 2: April 29, 2026

Common plots for quantitative data with qualitative variables

[Common plots for quantitative data with qualitative variables](./week4/index.html)

In-Class Exercise:

Recreate `imag1.jpeg` and `img2.jpeg`. Identify the drawbacks of the given chart, if any, and suggest suitable improvements to make the visualization clearer, more effective, and easier to interpret.

Data source for `image 1`: [https://ec.europa.eu/eurostat/databrowser/view/edat_aes_l21/default/table?lang=en&category=educ.educ_lang.educ_lang_00.edat_aes_l2](https://ec.europa.eu/eurostat/databrowser/view/edat_aes_l21/default/table?lang=en&category=educ.educ_lang.educ_lang_00.edat_aes_l2)

## Week 3: 6 May 2026

[Visualizing Distributions](https://tstdataviz.netlify.app/slides/dis22#1)

## Week 4: 13 May 2026

[Spatial Data Visualization](https://thiyanga-dataviz.netlify.app/slides/sp_viz#1)

## Week 5: 20 May 2026

Interactive Spatial Data Visualisation - In class demonstrations

## Week 6: 27 May 2026

[Time Series Data Visualisation](https://thiyangt.github.io/datavisualisation/week5/#/title-slide)

Task 1: See Google Classroom

## Week 7: 2 June 2026

[Visualisation with timetk](./week7/index.html)

[Interactive timeseries visualisation](./week8/index.html)

Creating Quarto dashboard - In class demo

[Reference](https://thiyangt.github.io/dashboardworkshop/#/title-slide)

## Mid evaluation - Mini Project

Assignment announced date: 2 June 2026

Use Sri Lanka dengue data from the denguedatahub package to develop an interactive dashboard for exploring dengue situation in Sri Lanka. In addition, prepare a short report explaining the data, the methods used for analysis (such as trend and seasonality exploration), and the key findings, including any observed patterns or outbreak periods.

Due date: ~17 June 2026~ 10 July 2026

Please upload all your documents as a single file to the “Mid Evaluation” tab in Google Classroom. Ensure that the file is named using your index number.

## Week 8: 9 June 2026

[Dimension Reduction Methods](https://thiyangt.github.io/DR/)

## Week 9: 16 June 2026

[Cross talk with plots](./week9/interactive_dataviz.R)

## Week 10-11: 24 June 2026/ 1 July 2026

Dengue Data Dashboard Visualisation

## Week 12: 8 July 2026

[Data Quality Analysis](https://thiyangt.github.io/tstalagala-MIS4141/ch2.html)

## Week 13: 15 July 2026

Task 1: Obtain a suotable visualisation to visualise mandatary and voluntary maternity leave in EU 2024

Link to data: [https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-06-02/eplp.csv](https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-06-02/eplp.csv)


```r
library(tidytuesday)
data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-06-02/eplp.csv') |> 
  mutate(across(where(is.numeric), ~replace_values(.x, -98 ~ NA))) 
```

Task 2: Visualise measles data

```r
cases_month <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_month.csv')
```

Task 3: 


Other plots


[Plot 1](https://www.google.com/search?q=Radar+bar+chart+%28min+vs+max+temperature%29+%2Btidytuesday+%2Bsunburst+plot&sca_esv=53ab19e28dc03dd8&udm=2&biw=1280&bih=612&sxsrf=APpeQnulKR8MKgjRFM-yv5YfFLz5Y6WQdg%3A1784080070218&ei=xuZWavLrDNCE4-EPxIf32AE&ved=0ahUKEwjy5teWyNOVAxVQwjgGHcTDHRsQ4dUDCBE&uact=5&oq=Radar+bar+chart+%28min+vs+max+temperature%29+%2Btidytuesday+%2Bsunburst+plot&gs_lp=Egtnd3Mtd2l6LWltZyJEUmFkYXIgYmFyIGNoYXJ0IChtaW4gdnMgbWF4IHRlbXBlcmF0dXJlKSArdGlkeXR1ZXNkYXkgK3N1bmJ1cnN0IHBsb3RI4yhQowFY9CZwAXgAkAEAmAFEoAHKB6oBAjE1uAEDyAEA-AEBmAIAoAIAmAMAiAYBkgcAoAe0AbIHALgHAMIHAMgHAIAIAQ&sclient=gws-wiz-img#sv=CAMSURoyKhBlLVdWb3BZYnpSY2FDOFNNMg5XVm9wWWJ6UmNhQzhTTToOdTVNaWRfMzdwRVhCV00gBCoXCgFzEhBlLVdWb3BZYnpSY2FDOFNNGAEwARgHIO3eiY0ISggQARgBIAEoAQ)

[Plot 2](https://observablehq.com/@thetylerwolf/day-17-radial-bar-chart)

## R Interface to D3 Visualizations

[Click here](https://rstudio.github.io/r2d3/)

## Movement Data Visualisation

Click [here](/week13/index.html)





